"""创建Employee表的迁移脚本

Revision ID: e52c54c2f4dd
Revises: 5937920ab658
Create Date: 2025-09-14 13:48:59.995217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52c54c2f4dd'
down_revision: Union[str, Sequence[str], None] = '5937920ab658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_emp', sa.Column('entry_date', sa.Date(), nullable=False, comment='入职时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_emp', 'entry_date')
    # ### end Alembic commands ###
